### ISSUE TITLE
error while saving!

### ISSUE THREAD

**Issue by Lapudavo** [hallgeirl/gd-item-search#14]
[error img](https://imgur.com/a/UFIN9nK)

any solution? :(

**Comment by hallgeirl** [comment]
Hi!

I've seen this before when Grim Dawn is running when loading items from the item DB (when saving), due to some files being locked temporarily. Can you try saving without Grim Dawn actually running and see if that solves it?
I do think it should be solved in the application itself, but this would be the workaround for now.

**Comment by Lapudavo** [comment]
>  Can you try saving without Grim Dawn actually running and see if that solves it?
It did not help. Still same error

**Comment by hallgeirl** [comment]
Can you attach the Log.txt file please, which resides in the same directory as the Grim Search's .exe file?

**Comment by Lapudavo** [comment]
```
DEBUG 2018-08-18 19:53:49,602   109ms GDISLog                .ctor              - Main window initialized.
DEBUG 2018-08-18 19:54:50,546 61053ms GDISLog                LoadAllItems       - Item cache not found - reading from g:\GrimDawn
DEBUG 2018-08-18 19:54:50,561 61068ms GDISLog                ReadItemsFromFiles - Processing: g:\GrimDawn\database\database.arz
DEBUG 2018-08-18 19:54:50,577 61084ms GDISLog                Extract            - Found ArchiveTool.exe in g:\GrimDawn
DEBUG 2018-08-18 19:54:50,577 61084ms GDISLog                Extract            - Created temp dir at: C:\Users\xyz\AppData\Local\Temp\GDArchiveTempPath
DEBUG 2018-08-18 19:54:50,577 61084ms GDISLog                Extract            - Executing: g:\GrimDawn\ArchiveTool.exe "g:\GrimDawn\database\database.arz" -database C:\Users\xyz\AppData\Local\Temp\GDArchiveTempPath
DEBUG 2018-08-18 20:03:07,508 558014ms GDISLog                Extract            - Execution finished.
DEBUG 2018-08-18 20:03:07,508 558014ms GDISLog                Extract            - g:\GrimDawn\database\database.arz was successfully extracted to C:\Users\xyz\AppData\Local\Temp\GDArchiveTempPath
DEBUG 2018-08-18 20:03:33,133 583639ms GDISLog                ReadItemsFromFiles - Processing: g:\GrimDawn\gdx1\database\GDX1.arz
DEBUG 2018-08-18 20:03:33,133 583639ms GDISLog                Extract            - Found ArchiveTool.exe in g:\GrimDawn
DEBUG 2018-08-18 20:03:33,133 583639ms GDISLog                Extract            - Created temp dir at: C:\Users\xyz\AppData\Local\Temp\GDArchiveTempPath
DEBUG 2018-08-18 20:03:33,148 583655ms GDISLog                Extract            - Executing: g:\GrimDawn\ArchiveTool.exe "g:\GrimDawn\gdx1\database\GDX1.arz" -database C:\Users\xyz\AppData\Local\Temp\GDArchiveTempPath
DEBUG 2018-08-18 20:03:35,758 586264ms GDISLog                Extract            - Execution finished.
```

**Comment by hallgeirl** [comment]
Hi,
I realize this is a VERY late response (I have not worked that much on this tool for a while). 
Now however, there's a new prerelease/beta version out (v0.3.0) here: https://github.com/hallgeirl/gd-item-search/releases/tag/v0.3.0. This should hopefully no longer be an issue. That version is a major rewrite - but relevant to your case is that I've removed the use of ArchiveTool (which is the tool shipped with GD). Instead, Grim Search now does the extraction in-process. 

There could still be issues of course, and if so, feel free to reopen this with any error messages you then get.
